import type { Product } from './types';

/**
 * Generate mock product data for testing
 */
export const mockProducts: Product[] = [
	{
		name: 'iPhone 15 Pro',
		description:
			'Latest Apple smartphone with A17 Pro chip and titanium design',
		price: 999.99,
		category: 'smartphones',
		brand: 'Apple',
		inStock: true,
		tags: ['flagship', '5G', 'iOS'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'Samsung Galaxy S24 Ultra',
		description: 'Premium Android phone with S Pen and excellent camera',
		price: 1199.99,
		category: 'smartphones',
		brand: 'Samsung',
		inStock: true,
		tags: ['flagship', '5G', 'Android', 'S-Pen'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'MacBook Pro 16"',
		description: 'Powerful laptop with M3 Max chip for professionals',
		price: 2499.99,
		category: 'laptops',
		brand: 'Apple',
		inStock: true,
		tags: ['professional', 'M3', 'macOS'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'Dell XPS 15',
		description: 'High-performance Windows laptop with beautiful display',
		price: 1799.99,
		category: 'laptops',
		brand: 'Dell',
		inStock: false,
		tags: ['professional', 'Windows', 'OLED'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'Sony WH-1000XM5',
		description: 'Premium noise-cancelling wireless headphones',
		price: 399.99,
		category: 'audio',
		brand: 'Sony',
		inStock: true,
		tags: ['wireless', 'noise-cancelling', 'premium'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'AirPods Pro (2nd generation)',
		description: 'Apple wireless earbuds with active noise cancellation',
		price: 249.99,
		category: 'audio',
		brand: 'Apple',
		inStock: true,
		tags: ['wireless', 'noise-cancelling', 'compact'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'iPad Air',
		description: 'Versatile tablet with M2 chip and Apple Pencil support',
		price: 599.99,
		category: 'tablets',
		brand: 'Apple',
		inStock: true,
		tags: ['tablet', 'M2', 'iPadOS'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'Samsung Galaxy Tab S9',
		description: 'Android tablet with S Pen and AMOLED display',
		price: 799.99,
		category: 'tablets',
		brand: 'Samsung',
		inStock: false,
		tags: ['tablet', 'Android', 'S-Pen', 'AMOLED'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'PlayStation 5',
		description: 'Next-gen gaming console with fast SSD and 4K graphics',
		price: 499.99,
		category: 'gaming',
		brand: 'Sony',
		inStock: true,
		tags: ['gaming', 'console', '4K'],
		createdAt: new Date().toISOString(),
	},
	{
		name: 'Nintendo Switch OLED',
		description: 'Portable gaming console with vibrant OLED screen',
		price: 349.99,
		category: 'gaming',
		brand: 'Nintendo',
		inStock: true,
		tags: ['gaming', 'portable', 'OLED'],
		createdAt: new Date().toISOString(),
	},
];
